name: Run Scraping Script with Selenium

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install the latest stable Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y

      # Step 4: Install ChromeDriver matching the installed Chrome version
      - name: Install ChromeDriver
        run: |
          pip install webdriver-manager
          chromedriver_autoinstaller = webdriver_manager.ChromeDriverManager()
          chromedriver_path = chromedriver_autoinstaller.install()
          echo "## ChromeDriver path: $chromedriver_path"

      # Step 5: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r web_scraping/requirements.txt

      # Step 6: Set up environment variables
      - name: Add environment variables
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
          echo "SCRAPE_LIMIT=${{ secrets.SCRAPE_LIMIT }}" >> .env

      # Step 7: Run the scraper script
      - name: Run scraper
        run: python web_scraping/scrape.py
